### PR TITLE
Add sortByColumn user config

### PR DESCRIPTION
**Pull request by felixfung**
Implements #38 by giving user config option to sort by column or row.

Updates config file comment.

Renames MainWin->cod to MainWin->clientondesktop.

Introduce MainWin->focuslist for future purpose.

@dreamcat4 I would like to make boxy layout and sort by column to be default, because I am guessing most users intend to use skippy for expose, rather than alt+tab. Am I correct?

### CODE REVIEW

**Comment by dreamcat4** [comment]
thanks felix for working on this. it was much needed

> @dreamcat4 I would like to make boxy layout and sort by column to be default, because I am guessing most users intend to use skippy for expose, rather than alt+tab. Am I correct?

i am not at all sure about the actual user base usage. perhaps it might be helpful to do some poll or survey idk if we would get many replies though!

what i am happy about is that you did the work, so you can make as your preferred option. but my main comment is that whichever default configuration you choose... it should be reliable and not paint skippy in a worse light for the sake of forcing users towards testing less stable features. i.e. not turn people away because the out of box experience was bad and they did not realize or to bother to configure it.

please let other users some comment here. as to their preferred default. and maybe we can @ some regular  users tho prevously participated in recent issues. to invite broader comment from regular user base. many thanks

**Comment by dreamcat4** [comment]
> If you don't have huge objection I would like to merge this so I can work on https://github.com/dreamcat4/skippy-xd/issues/53 on top of this?

It depends mostly if those alt+tab prev-next navigation does get broken again: this was the problem last time. And was why previous attempt got reverted.

So in my mind, it's less about the default setting here, and more about not breaking existing functionality in those modes. Which you do not seem to test / are less familiar / do not use.

For the default options / example rc... it can be instead it's own seperate issue to be discussed at leisure amongst broader community. So that aspect does not need to hold up here.

But also: please bear in mind my comment, as i do not wish to have to reverse new functionalities you are adding to skippy. I hope that makes sense?

**Comment by felixfung** [comment]
Sure. I have tested to my satisfaction, but as you said I'm less familiar with this usage. Hence I value your input very much :)

I hope this PR is ok by your testing?

**Comment by dreamcat4** [comment]
> I hope this PR is ok by your testing?

@felixfung unfortunately no, it isn't! This is having the same sort of weird broken behaviour as was the last time.

What I am not sure if this is an issue that you can see on your WM/DE. Because I am on KDE here, but basically it's just not acceptable at all. The alt+tab seems getting entirely broken by this PR

**Comment by dreamcat4** [comment]
I should take some screenshot etc. or video to demonstrate. you will need to wait a bit for that. At the moment I just did the following skippy config:

```sh
# Copy this to ~/.config/skippy-xd/skippy-xd.rc and edit it to your liking
#
# Notes:
#
# - colors can be anything XAllocNamedColor can handle
#   (like "black" or "#000000")
#
# - distance is a relative number, and is scaled according to the scale
#   factor applied to windows
#
# - fonts are Xft font descriptions
#
# - booleans are "true" or anything but "true" (-> false)
#
# - opacity is an integer in the range of 0-255
#
# - brighness is a floating point number (with 0.0 as neutral)
#
# - if the update frequency is a negative value, the mini-windows will only
#   be updated when they're explicitly rendered (like, when they gain or
#   lose focus). otherwise updateFreq is how many updates per second (fps)
#
# - the 'shadowText' option can be a color or 'none', in which case the
#   drop-shadow effect is disabled
#
# - Picture specification:
#   [WIDTHxHEIGHT] [orig|scale|scalek|tile] [left|mid|right] [left|mid|right]
#   [COLOR|#FFFFFFFF] [PATH]
#
# - keysUp, keywDown, eysLeft, keysRight:
#   selects the window in the direction compared to the current selected window,
#   without wrapping
#
# - keysPrev, keysNext:
#   selects window previous or next to current one, in up->down, left->right
#   ordering, wrapping per column and per row
#   
#   Examples:
#   background = 500x400 tile right mid #FF0000 /home/richard/screenshots/256.png
#   background = orig mid mid #FF000080
#
# - [bindings] for miwMouse[1,2,3] can bind to "no" (do nothing), "focus"
#   (focus to window), "iconify", "shade-ewmh" (toggle window shade state),
#   "close-icccm" (close window with ICCCM method), "close-ewmh" (close
#   window with EWMH method), or "destroy" (forcefully destroy the window).
#
# - [bindings] key* = is a list of valid XWindows KeySym identifiers, case
#   sensitive and <space> seperated list. Run the program 'xev' to find them.
#
# - [bindings] modifierKeyMasks* = is a list of valid XWindows modifier key
#   bitmask identifiers, as defined in the /usr/include/X11/X.h header file.
#

[general]

# layout=boxy is favoured by expo usage
# layout=xd is favoured by alt+tab usage
layout = boxy

# sort by row or sort by column
# sorting by column is favoured by boxy layout
# sorting by row is favoured by xd layout
sortByColumn = false

distance = 50
useNetWMFullscreen = true
ignoreSkipTaskbar = true
updateFreq = 60.0

# set = 0 to switch off animations
animationDuration = 0

lazyTrans = false
pipePath = /tmp/skippy-xd-fifo

# Move the mouse cursor to the next highlighted window, straight after launching skippy
movePointerOnStart = false

# Move the mouse cursor over the currently highlighted window, when using the keyboard to navigate between windows
movePointerOnSelect = false

# After activating the selected window, the skippy window picker is dissmissed. Then move mouse cursor to the center of the selected window.
# Otherwise (if false), the mouse cursor will remain in the location where it was at the time when skippy was dismissed.
movePointerOnRaise = false

switchDesktopOnActivate = true
useNameWindowPixmap = false
forceNameWindowPixmap = false
includeFrame = false
allowUpscale = true
showAllDesktops = true
showUnmapped = true
cornerRadius = 5
preferredIconSize = 48
clientDisplayModes = thumbnail-icon thumbnail icon filled none
iconFillSpec = orig mid mid #00FFFF
fillSpec = orig mid mid #FFFFFF
# background = /home/id/r.png

windowHistory = true
startPosCenter = true

# startPos = first | center | fixed | lastActive

startOnLastActive = true

# windowListOrderBy = xy_position | activation_history


#startPosOffset = 0

[xinerama]
showAll = true

[normal]
tint = black
tintOpacity = 0
opacity = 200

[highlight]
tint = #101020
tintOpacity = 64
opacity = 255

[tooltip]
show = true
followsMouse = true
offsetX = 20
offsetY = 20
align = left
border = #ffffff
background = #404040
opacity = 128
text = #ffffff
textShadow = black
font = fixed-11:weight=bold

[bindings]
miwMouse1 = focus
miwMouse2 = close-ewmh
miwMouse3 = iconify
keysUp = Up w
keysDown = Down s
keysLeft = 
keysRight = 
keysPrev = Left b a
keysNext = Right Tab f d
keysExitCancelOnPress = Escape BackSpace x q
keysExitCancelOnRelease =
keysExitSelectOnPress = Return space
keysExitSelectOnRelease = Super_L Super_R Alt_L Alt_R ISO_Level3_Shift
keysReverseDirection = Tab
modifierKeyMasksReverseDirection = ShiftMask ControlMask
```

**Comment by felixfung** [comment]
What if you do layout = xd and sortByColumn = false?

**Comment by felixfung** [comment]
The object of this PR, sortByColumn, gives proper behaviour for both true and false value?

**Comment by dreamcat4** [comment]
also there is non-sequential transition (not ordered) with `layout = xd` and `sortByColumn = true`

It seems like the algorithm for sorting the cw order (of the list) works in only 2 of the 4 possible configurations


|layout| sortByColumn|prev-next ordering|correct?|
|-|-|-|-|
|boxy|true|sequential|the feature is broken on my kde|
|boxy|false|has 3 'jumps'|no|
|xd|true|sequential|yes|
|xd|false|has 3 'jumps'|no|

**Comment by dreamcat4** [comment]
> The object of this PR, sortByColumn, gives proper behaviour for both true and false value, when layout = xd?

on KDE here, as per the truth table above (just posted in last comment). It only works with `false` value.

Thing is I cannot seem to get the boxy layout looking good on KDE desktop. So maybe something else is wrong, in terms of how it should normally look. I am not certain.

What it means: maybe not a good default option still.

**Comment by felixfung** [comment]
Ignoring the boxy layout for now (certainly we have to fix it later)...

Just want to make sure jit's not typo that sortByColumn = true gives correct behaviour? Because it is new feature. And what do you mean by 3 jumps?

layout | sortByColumn | prev-next ordering | correct?
-- | -- | -- | --
xd | true | sequential | yes
xd | false | has 3 'jumps' | no

**Comment by dreamcat4** [comment]
> Ignoring the boxy layout for now (certainly we have to fix it later)...
> 
> Just want to make sure jit's not typo that sortByColumn = true gives correct behaviour? Because it is new feature. And what do you mean by 3 jumps?
> layout 	sortByColumn 	prev-next ordering 	correct?
> xd 	true 	sequential 	yes
> xd 	false 	has 3 'jumps' 	no

Ah yes sorry, you caught it! I messed up the table there. Those last 2 rows should be swapped around. I fix the table now:

|layout| sortByColumn|prev-next ordering|correct?|
|-|-|-|-|
|boxy|true|sequential|the feature is broken on my kde|
|boxy|false|has 3 'jumps'|no|
|xd|true*|**has 3 'jumps'***|**no***|
|xd|false*|**sequential***|**yes***|

*typo error, values are corrected

**Comment by felixfung** [comment]
I see what is happening :)

If you look at sort_cw_by_column(), you see it is the intended behaviour:

The window focus ordering is left to right according to the centre of the window, then top to bottom according to the centre of the window. Sometimes you think the window is going bottom to top, because of small x offset according to the centre of the window.

There is no bug here in this PR, just that sorting by column and XD layout does not match. I hope we have clarified this issue?

One possibility is to take away the user config for sort by column. Rather, each layout algorithm becomes responsible for their own sorting. E.g. boxy determines sorting by column, XD determines sorting by row, etc if new layouts are introduced in the future. Then if apparent jumps happen, it is the layout's fault.

Since we are here, we can talk about the other issues?
- Black windows: I am guessing that is from unmapped windows that's following old behaviour before iconized PR rather? I have observed that happening to me from time to time, and I am guessing it is from the bad pixmap and bad match X errors, which may also be the root cause of #54.
- Boxy layout: I would like to see a video if possible?

**Comment by dreamcat4** [comment]
### 1) column sort algorithm

ah ok thanks for explaining this.... yes i do understand now better what is doing. my feeling then:

this is ok to merge here as-is. the column sort option. then in future we could consider at leisure any other type of 'more advanced' additional algorithm. as extra optional enhancement....

it can be possible perhaps to improve over these. yet we can still keep these 2 (row and column) as being primary methods. and simpler algorithm. so this then protects us in case a more complex algorithm would introduce it's own complexity or new bugs.

in terms of locking the sort algorithm to the layout method - it does have a point but then it is less of user freedom. for now i think we should keep independent of each other. for example:

a good idea in future may be to do xd layout that is actually fully grid aligned. or any other new layout styles. then this existing column algorithm exactly you have done... then may work fine with those future layout style. (which does not exist yet).

so hopefully those reasoning makes sense. and i am happy to go ahead here with your existing proposed column sort, for those specific set of reasons.


### 2) black boxes (seems bug)

raised as separate issue #65 

### 3) boxy layout

yes ok video for boxy layout i shall make to follow soon. it will upload later

**Comment by felixfung** [comment]
To continue topic regarding the potential intrinsic bonding between layout and next/prev sorting: say for the sake of argument in the future we implement a layout where windows are arranged in a circle (I have some recollection that was an option in early versions of Compiz, then x-y coordinates would be bad next/prev sorting, rather angle wrt circle centre would be the way.

Anyway that would be for the future.

**Comment by dreamcat4** [comment]
> Boxy layout: I would like to see a video if possible?

3) OK is raised now as seperate issue #70

**Pull request merged**
