### PR TITLE
Fixed pointer and live preview after animation.

### PR DESCRIPTION
**Pull request by felixfung**
Potentially related: when I press escape, no window is focused? Shouldn't behaviour be to focus on previously focused window?

### CODE REVIEW

**Comment by felixfung** [comment]
I tried put in clientwin_handle() this:

		else if (arr_keycodes_includes(cw->mainwin->keycodes_ExitCancelOnPress, evk->keycode))
		{
			printfef("(): Quitting.");
			if (mw->revert_focus_win) {
                mw->client_to_focus = mw->revert_focus_win;
            }
            else {
                mw->client_to_focus = NULL;
            }
            return 1;
		}

and somehow gets segfault with this backtrace?

0x00005555555651d9 in childwin_focus (cw=0x6001a3) at src/clientwin.c:478
478		session_t * const ps = cw->mainwin->ps;
(gdb) p ps
$1 = (session_t * const) 0x0
(gdb) bt
#0  0x00005555555651d9 in childwin_focus (cw=0x6001a3) at src/clientwin.c:478
#1  0x000055555555d260 in mainloop (ps=ps@entry=0x55555557ce50, 
    activate_on_start=activate_on_start@entry=true) at src/skippy.c:704
#2  0x000055555555a765 in main (argc=1, argv=0x7fffffffe8b8)
    at src/skippy.c:1659
(gdb) f 1
#1  0x000055555555d260 in mainloop (ps=ps@entry=0x55555557ce50, 
    activate_on_start=activate_on_start@entry=true) at src/skippy.c:704
704					childwin_focus(mw->client_to_focus);
(gdb)

**Comment by felixfung** [comment]
> I tried put in clientwin_handle() this:
> 
> ```
> 	else if (arr_keycodes_includes(cw->mainwin->keycodes_ExitCancelOnPress, evk->keycode))
> 	{
> 		printfef("(): Quitting.");
> 		if (mw->revert_focus_win) {
>             mw->client_to_focus = mw->revert_focus_win;
>         }
>         else {
>             mw->client_to_focus = NULL;
>         }
>         return 1;
> 	}
> ```
> 
> and somehow gets segfault with this backtrace?
> 
> 0x00005555555651d9 in childwin_focus (cw=0x6001a3) at src/clientwin.c:478 478 session_t * const ps = cw->mainwin->ps; (gdb) p ps $1 = (session_t * const) 0x0 (gdb) bt #0 0x00005555555651d9 in childwin_focus (cw=0x6001a3) at src/clientwin.c:478 #1 0x000055555555d260 in mainloop (ps=ps@entry=0x55555557ce50, activate_on_start=activate_on_start@entry=true) at src/skippy.c:704 #2 0x000055555555a765 in main (argc=1, argv=0x7fffffffe8b8) at src/skippy.c:1659 (gdb) f 1 #1 0x000055555555d260 in mainloop (ps=ps@entry=0x55555557ce50, activate_on_start=activate_on_start@entry=true) at src/skippy.c:704 704 childwin_focus(mw->client_to_focus); (gdb)

Fixed in separate PR

**Comment by dreamcat4** [comment]
Hi,

> Potentially related: when I press escape, no window is focused? Shouldn't behaviour be to focus on previously focused window?

Yes it should.
I am not certain when you are seeing this observed behavior. 

Are you saying that your animations code has already broken / regressed this specific behaviour?

If yes --> is this a bug that is causing skippy to crash on quit? Before it can (on exit proceedure) refocus the last active window?

If no -->

Is it specific to:

* your current code (that you are running, with your latest changes)
* something related to your chosen DE/WM (mine is KDE plasma xorg here)
* your invocation method / user settings for skippy

but what I can say is:

throughout my whole usage of skippy, this was not a correct or observed normal operating behaviour for me. So I am not sure at all what is happening.

But here is (on my machine, using the skippy code before any of your changes):

When i type inside my currently active terminal application (tilix)

```sh
$ skippy-xd-runner --activate
```

Then while skippy is displaying, then KDE's version of "no focussed window", the window name becomes **"KDE Plasma Desktop"**. Which is when skippy is open and showing it's previews window. This is the same window state as "Show Desktop" action in KDE.

Ok. So then skippy is open, and I press the excape key. Then skippy exits. And the currently active window changes back to the original applicaiton i was previously in, which is back to Tilix app.

So either skippy is setting that during it's quitting routine. Or my DE is remembering the previous active window. And restoring the focus back to that. I am not sure! ...maybe skippy is supposed to be this task when it quits? Then that would be somewhere in it's exit routines.

Sorry I cannot be much help. You were too brief perhaps with explaining the context / situations. If this is not some simple and isolated bugfix. (that if it affects animations code paths and nothing else, or it's more general).

**Comment by felixfung** [comment]
To clarify:

This PR sets the pointer at the current window at the end of animation. The code change should be self explanatory?

 I have tested it to my satisfaction, but wondering what your observed behaviour is with/without this fix.

Regarding the escape key behaviour, I am guessing your DE is remembering the previous active window. I have created https://github.com/dreamcat4/skippy-xd/pull/25, and tested that to my satisfaction. I think that PR is self explanatory?

I do not use skippy runner, and run skippy "naked". I am trying to understand all the context behind skippy runner?

**Comment by dreamcat4** [comment]
> This PR sets the pointer at the current window at the end of animation. The code change should be self explanatory?

ok

> I have tested it to my satisfaction, but wondering what your observed behaviour is with/without this fix.

sorry but i do not enable animation - because i have no use for this specific feature currently. however i am happy merging animation in the knowledge that others will want to try this / use this feature (for expose type invocation). and it's certainly a valid and desirable feature - i feel it might be helpful to find other users here in issues (who are interested) to better test animations feature.

> Regarding the escape key behaviour, I am guessing your DE is remembering the previous active window. I have created https://github.com/dreamcat4/skippy-xd/pull/25, and tested that to my satisfaction. I think that PR is self explanatory?

ok

> I do not use skippy runner, and run skippy "naked". I am trying to understand all the context behind skippy runner?

i have tried to explain in the readme.md about the function of skippy-xd-runner. it is also explained here:

https://github.com/dreamcat4/skippy-xd/blob/master/skippy-xd-runner#L3-L11

it is an optional helper / supervisor script that is useful for alt+tab style invocations. you may indeed no need to require it for expose style / or single keypress invokation

**Pull request merged**
