### PR TITLE
Virtual desktop Pager functionality

### PR DESCRIPTION
**Pull request by felixfung**
This is NOT full feature implementation of #56.

What is implemented:
- New entry point to paging, via command line options and pipe commands.
- Functional virtual desktop paging functionality.

What is NOT implemented:
- Currently the user selects a window within all virtual desktops. However, windows may be blocked behind other windows and not be visible.
- A full implementation is where users select desktops, rather than windows. The key bindings and visual interface of the desktop selection would parallel that of current window selection.
- I think the proper way to implement desktop selection is to create new ClientWins, one per virtual desktop, then point MainWin->focuslist to this new list of ClientWins. I have been having problem to get the visual presentation of it working. Hence, this is a partial PR.

Despite this being an incomplete feature, I am inclined to merge it once we test it to be bug-free. The reason is that it does not interfere with existing functionalities, and also despite being incomplete feature, I personally find it very useful. Feedback?

While this is under review, or while it is merged and before I fully implement, I would like to shift focus on fixing existing issues, especially #52, #54, #65.

Btw the proper selection ordering for desktops is top to bottom, left to right, row-by-row rather than column-by-column, which is implemented in this PR.

### CODE REVIEW

**Comment by vredesbyyrd** [comment]
Testing for the last hour and I have not run into anything, ill report back if that changes. 

And wow! Very useful indeed. Its a very logical, simple way to discern where you want to navigate to. Love it. Ill test on the other other WM I have installed as well.

**Comment by vredesbyyrd** [comment]
So after some testing I may have run into a couple things. I don't know what expected behavior is under the following circumstances, but when using a 2nd display + `xinerama = true` the pager "metaphor" seems to break down a bit. I know #66 is not fully implemented, so this is probably expected. 

**Setup:** 

WM: 2bwm
Primary display: 1920x1080 (laptop)
2nd display: 1920x1200
4 primary workspaces + 2nd display

In the below screenshot the`mpv` video window is fullscreen on the 2nd display in `workspace 0`. The grey edge of a window (upper right) is fullscreen on 2nd display in `workspace 1`. 

 I'm not sure if you have any plans to implement `xinerama` windows, or ideas on how to visualize them. Perhaps putting xinerama windows into there own virtual desktop/workspace just like any _normal_ workspace would be a simple, clean way to visualize them. 

Screenshot from 2023-03-30 14-21-03

**Comment by felixfung** [comment]
I would like xinerama to work for paging, but I don't know how to set up, in fact I don't have a spare monitor...

Probably I would try to conjure up some code and ask you to test :)

**Comment by vredesbyyrd** [comment]
Right on, that's understandable! 

Well if you do conjure up some xinerama code I will gladly test :)

**Comment by felixfung** [comment]
I'm going to merge this and work on xinerama.

**Pull request merged**
