### PR TITLE
Boxy layout

### PR DESCRIPTION
**Pull request by felixfung**
Draft PR, PLEASE DO NOT MERGE IT without extensive testing for 1-2 weeks!

The original skippy layout seems to be doing a straightforward left->right, up->down layout ordered by the client window ordering or similar, without taking into account the original window positioning. Hence, animation between window movements between original and final positioning becomes non-optimal and not perfectly efficient for frequent use.

This is an attempt to introduce "better" layout, with these considerations:

0. there are non-unique ways to put windows into a screen without overlapping
1. for user intuition, we want the layout to be close to the original positions
2. when two windows hold identical positions, then we have tradeoffs
3. screens are often either long (when rotated 90) or wide, and layouts should capitalize on that
4. sizes of windows will enlarge/shrink by the same factor, since size is an important visual cue to identify windows
5. the screen size aspect ratio, the windows original total occupied screen space aspect ratio, and windows may be overlapping or hold identical spaces, and the final occupied screen aspect ratio, and not have to be identical
6. boxy layout slots are more screen efficient, as well as being easier for user's eyes

This "boxy" layout algorithm is thus:

1. scan through windows to find the smallest window size, this forms the slot size
LOOP:
2. create 2D array of slots, where each element holds the number of windows in that slot, map each slot to the occupying windows, if there are any empty rows/columns, remove and go to start of loop
3. a. expand:
       loop slots right->left, bottom->top, for each slot with collision,
       insert right/below new row/columns based on screen aspect ratio
       move windows to right/down, sorted by "affinity":
       which is the number of slots in that direction minus those
           in opposite direction, times the windows' number of slots
       so the the higher the affinity, the further from the original slot
    b. contract:
       loop slots left->right, top->bottom, for each free slot,
       compare window below, window rightside, window below and right side
       to current slot, sorted by affinity,
       and whether current slots can fit the window
 4. END LOOP when no windows have been moved
 5. move windows to slots

To be honest this code is not great. I am not great dealing with C-style arrays and this custom linked list, so I put it in a giant function rather than more modularized sub-functions. I caught and fixed many off-by-one or index errors, but I would not be surprised if a few still exists. I think for every day use this code/implementation is OK, but I know if there are many many windows, or if there exists very small windows we get segfault. The reason I create this draft PR is so others can lend eyeballs to all these indices :P

Outstanding issues:
- Identify and squish bugs
- The current algorithm creates a triangular layout as ideal, e.g.:
        o o o
        o o
        o
  This is not optimal use of screen space. Additional work on this algorithm can optimize it.
- The window selection behaviour of richardgv was that left, up, right, down corresponds to focusing on window in that direction, without wrapping. Some newer commits changed left and right behaviour to "prev" and "next"? I think a proper behaviour would be left, up, right, down, and then in addition "prev" and "next" based left and right, but wraps to next line. Please correct me if I am wrong.
- Perhaps bugs introduced by my animation PR: mouse is no longer necessarily focused on current window, and live preview of windows (e.g. movies) is not triggered until mouse is focused on a window.

### CODE REVIEW

**Comment by dreamcat4** [comment]
this is indeed a challenging and difficult feature to add, given the way the code is. haha

but also, with this sorts of works to improve skippy, you are more than welcome to become maintainer going forwards. (should you wish)

for that, i would like to create a transfer ownership request on the repo. because this will allow you to get control over the existing issues in the tracker and so on...

i feel your code quality and general work is at a necessary level, and may you have a great attitude towards this project. i hope you will please consider maintainership

of course if there is anything else of input you think i might be able to help with, (then will try to assist). just mainly my activity working on skippy here is over. so it is an ideal time to pass on to another

**Comment by felixfung** [comment]
Thank you for the offer, I am honoured by the prospect.

At this point, I don't think it is a good idea for me to become maintainer:
- After this set of PRs on animation, layout, focus, my itch on this project is scratched.
- I do not use daemon mode, prev/next, or use skippy-xd as alt-tab. Nor do I experience any segfaults or missing minimized windows or X events. Hence, someone who DOES experience these would be the one to drive the project forward.
- I know nothing about X11 or WMs. Again knowledge in these probably are required to drive the project forward.

What I hope is that after the current set of features and bug fixes, skippy-xd would gain new traction, and someone else can step up? I would be happy to lend an eye on subsequent changes.

**Comment by dreamcat4** [comment]
ah indeed, that is a valuable feedback. indeed i agree. but we can at least add you as a collaborator here. for some extra permissions. it is the least i can do

**Comment by felixfung** [comment]
Please test this along, with and without other PRs.

I have tested by having 8+ windows and kept launching this script and skippy:

#!/usr/bin/perl

@window_ids = split( "\n", `xdotool search --onlyvisible . 2>/dev/null` );

foreach $wid (@window_ids) {
    $x  = int(rand(20)) * 80;
    $y  = int(rand(20)) * 50;
    $xx = int(rand(20)) * 80 % 1920; $xx = $xx - $x;
    $yy = int(rand(20)) * 50 % 1080; $yy = $yy - $y;
    `xdotool windowmove $wid $x $y`;
    `xdotool windowsize $wid $xx $yy`;
}

**Comment by felixfung** [comment]
I encourage trying out the boxy layout. I personally find it quite superior to the original layout algorithm, because it tries to preserve the original window position, it is quicker for the user to track which window is which, kind of the whole point of the expose feature?

By the way I experience segfault every now and then, when I invoke skippy on all desktops. I suspect the root cause to be similar to #32: due to arithmetics between signed and unsigned ints, in particular the total_width and total_height in layout.*. So if testers experience segfault, can try to fix+test this.

**Comment by dreamcat4** [comment]
> I encourage trying out the boxy layout. I personally find it quite superior to the original layout algorithm, because it tries to preserve the original window position, it is quicker for the user to track which window is which, kind of the whole point of the expose feature?

I did try it briefly yesterday, however i observed some sort of buggy behaviour or weirdness. It might be a situation that occurs when in different WM/DE (than your own system), i am not certain

> By the way I experience segfault every now and then, when I invoke skippy on all desktops.

Well here is a story that matches that one:

The stability of code is important. For example (from myself, not related to yours) however I still to this day have long term uncommitted code on my local disk for skippy. Where, for the improvement that i was working on, there is an unknown segfault that occurs every so often. Which is not repeatable or logical enough to actually find the root cause of the issue. Yet it occurs just 'too often enough' to be considered a clear regression in stablility. To the point where I cannot feel it's stable enough to upload / share. For example i might invoke skippy 15 times (or 17 times), then segfault occur. And it's probably 1 single bug.

This i felt was too much a regression in stability to let that code publicly. Since the existing version in git was already entirely 100% rock solid. Just i could never find the damn segfault!

Hopefully my feedback is something helpful?

Overall my long term experience with skippy has been that the nature of this code is not really having very much safety net. That the C rigor needs to be mostly self-imposed. It is good at letting you dig holes for yourself.

Sorry that is not a direct practical help (for this bug). But perhaps also running through a tool like valgrind might pick up some warning / places to look? Just in general I am not very sure how else we can improve our code quality.

**Comment by felixfung** [comment]
IMHO, the nature of this app, unit tests or automated tests is not that applicable. Also, the vast possibilities of screen configurations ,windows usage, WM possibilities, make exhaustive testing and bug-free releases very difficult.

To me, the way to test for this app is to (1) manual tests after compilation; e.g. my testing of layout with randomizing window positions and sizes I still believe was a decent testing attempt (2) daily usage by different users; e.g. that was how I found additional segfaults.

In an ideal world, we can streamline this to make it more safe, by introducing a development branch in addition to master branch, where after code review, contributors can merge into development branch, and contributors and testers can use that on a daily basis for testing. After sufficient time estimated based on code complexity, the code can be merged into master.

Right now, due to lack of contributors, having an additional development branch is not that helpful, since the lack of testers mean bugs will probably surface AFTER merging into master anyway.

So, I would like to reiterate my message to ask for testers. For example segfault #43, I didn't uncover it until I tried daemon mode, a feature/code path I didn't use and was not familiar with. Or the buggy behaviour or weirdness you experience on boxy layout, for me despite the rare segfault I experience, the code is quite usable and desirable, and I still don't know what is your experience. Given the wide variety of WMs and screen configurations, testers and reporters are much needed for the stability and usability of skippy-xd.

Also I would like to give skippy's code a bit of justice, I think it is fairly decent, reasonably workable, I have seen far worse code ;)

**Comment by felixfung** [comment]
> I encourage trying out the boxy layout. I personally find it quite superior to the original layout algorithm, because it tries to preserve the original window position, it is quicker for the user to track which window is which, kind of the whole point of the expose feature?
> 
> By the way I experience segfault every now and then, when I invoke skippy on all desktops. I suspect the root cause to be similar to #32: due to arithmetics between signed and unsigned ints, in particular the total_width and total_height in layout.*. So if testers experience segfault, can try to fix+test this.

It seems like the segfault is actually related to iconized windows, and perhaps #41 has fixed it.

**Comment by felixfung** [comment]
@dreamcat4 what sort of weirdness or bug do you experience here?

**Comment by felixfung** [comment]
@vredesbyyrd that is a good point. Right now there are two imperfections with the boxy layout:
1. It tries to organize slots as upper left triangles, e.g. shapes like this:
    o o o o
    o o o
    o o
    o

The imperfect use of screen space means smaller windows.
2. It tries to find the right number of rows and columns that conform to the screen aspect ratio. This attempt could be improved.

What I am thinking now, is to add config option to choose between "XD" and "boxy". Then users are free to choose :) Improvements on boxy layout can come in the future.

**Comment by vredesbyyrd** [comment]
> What I am thinking now, is to add config option to choose between "XD" and "boxy". Then users are free to choose :) Improvements on boxy layout can come in the future.

Good idea, I like it :)

**Pull request merged**
