### PR TITLE
Reintroduce filtering of minimized windows

### PR DESCRIPTION
**Pull request by maclomhair**
This change would reintroduce the option to hide minimized windows.

### CODE REVIEW

**Review by felixfung — COMMENTED** [review]
Should wm.c:621-625 be uncommented also?

Perhaps we can rename showUnmapped to showShadow?

**Comment by maclomhair** [comment]
Honestly, I don't know wether lines 621 to 625 shoud be uncommented as well. I am not able to test this code branch and if I'm not mistaken, most window managers today are EWMH compliant, even Mutter which is used by GNOME3...

Renaming I guess yes why not - although I consider something like `showMinimized` the most descriptive :)

**Comment by felixfung** [comment]
Thanks for the update.

Let's uncomment 621 - 625, I commented them out together with 608 - 609 in https://github.com/dreamcat4/skippy-xd/commit/92d4b155a4e2101362bd8b6d8fe0b2b223307967.

There is a difference between minimized and unmapped/shadowed :)

In the X world, unmapped is a specific window state, WMs often implement minimization, shading, and windows not on the current virtual window desktop by unmapping them (e.g. KDE unmaps windows on other virtual desktops also). Hence, depending on the WM, windows may well be unmapped but not minimized.

Therefore, showUnmapped is technically the most precise terminology. However, an end-user may not be familiar with the mapping/unmapping state. I feel showShadow may be a decent middle ground, especially given the [shadow] section in the config file.

**Comment by maclomhair** [comment]
I see, thank you for the explanation! I now changed the name of the option to showShadow and enabled the filtering for GNOME-compliant WMs in lines 621 to 625.

**Pull request merged**
