### PR TITLE
Remove config options

### PR DESCRIPTION
**Pull request by felixfung**
Remove some config options, which are either never used or always defaulted as true.

Out of these, the most "dangerous" (as in perhaps potentially erroneously removed) is keysReverseDirection and modifierKeyMasksReverseDirection, which according to my code inspection is never used. Anyhow, alternative ways to set up Alt-Tab and Shift-Alt-Tab exists.

### CODE REVIEW

**Comment by dreamcat4** [comment]
hmm. i am not sure what the impact is. but it is a bit concerning imho. these removals.

**Comment by dreamcat4** [comment]
i am going to revert this. because it is something which i currrently use.

**Comment by felixfung** [comment]
I look forward to coming to what's happening on this with you, and what to do with this option.

From my own experience attempting to use keysReverseDirection and modifierKeyMasksReverseDirection, they didn't work. From code inspection the code is never reached. And the current way I set up: set up hot key to do `skippy-xd --switch` and `skippy-xd --switch-prev` is guaranteed to work because there will not be conflict between user environment intercepting Alt-Tab from skippy-xd, and arguably this way is simpler for user to configure.

Would love to know how you set up.

**Comment by felixfung** [comment]
Btw I now also use skippy-xd for Alt-Tab, in addition to expose and paging. This app is awesome! :D

**Comment by dreamcat4** [comment]
felix, i agree with the other stuff. but the reversekeys direction was a thin added for a reason. and it just is not clear at the moment.

since i am behind master. so need enough actual time catch up and to test where you are at. before i can say one way or the other that the previous is fully deprecated. it takes time to go around and be double checking that.

until then that specific reversekeys will be  reverted the commit. and i shall let you know in due time. but for now please to wait on that one.

**Comment by dreamcat4** [comment]
to clarify: i wont be reverting the whole pr, just that single individual commit. assuming its self contained.

**Pull request merged**
