### PR TITLE
Fixed segmentation fault in --start-daemon

### PR DESCRIPTION
**Pull request by cezaris13**
With the help of @felixfung fixed `--start-daemon` segmentation fault. Issue: https://github.com/dreamcat4/skippy-xd/issues/43

### CODE REVIEW

**Comment by dreamcat4** [comment]
its better to git cherry pick felix's existing commit. rather than create a duplicate new commit, easier to not mess up the merging of felix's other open prs later on

are you familiar with git cherry pick? is pretty easy. if you don't do then i shall get around to soon enough

**Comment by cezaris13** [comment]
I haven't used cherry picking that much, but I think I cherry picked needed commit now.

**Comment by dreamcat4** [comment]
> I haven't used cherry picking that much, but I think I cherry picked needed commit now.

yes, you did correct here (for this pr). however its cleaner for the git history to just scrap this pr and raise a brand new one to contain only the needed commit.

don't worry - i shall sort this all out. but thank you for your efforts here, it is appreciated and valued these involvement / interest in the project

**Comment by dreamcat4** [comment]
closed by commit 61f979b

**Pull request closed without merging**
